// KINE 301 Visuomotor Learning Experiment
// 2 practice trials + 20 recorded trials.

const BLOCKS = [
  { name: 'Practice', trials: 2, delay: 0, moving: false, record: false },
  { name: 'Baseline', trials: 5, delay: 0, moving: false, record: true },
  { name: 'Delay', trials: 5, delay: 200, moving: false, record: true },
  { name: 'Delay + Sway', trials: 5, delay: 200, moving: true, record: true },
  { name: 'Restored', trials: 5, delay: 0, moving: false, record: true }
];

const SWAY_X = 65; // small left/right movement in pixels
const SWAY_Y = 38; // small up/down movement in pixels
const SWAY_FREQUENCY = 0.22; // slow movement
const MOVEMENT_THRESHOLD = 8;

const startScreen=document.querySelector('#start-screen'), experimentScreen=document.querySelector('#experiment-screen'), resultsScreen=document.querySelector('#results-screen'), game=document.querySelector('#game-area'), startCircle=document.querySelector('#start-circle'), target=document.querySelector('#target'), cursor=document.querySelector('#virtual-cursor'), message=document.querySelector('#message');
let participantId='',blockIndex=0,trialInBlock=0,globalTrial=0,trialActive=false,trialReady=true,targetShownAt=0,movementOnsetAt=null,rawMouse={x:0,y:0},shownMouse={x:0,y:0},mouseBuffer=[],pathLength=0,previousShown=null,maxProjection=0,targetBaseX=0,targetBaseY=0,swayStart=0,data=[];
const totalTrials=BLOCKS.reduce((n,b)=>n+b.trials,0);
function currentBlock(){return BLOCKS[blockIndex]} function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function updateLabels(){document.querySelector('#phase-label').textContent=currentBlock().name;document.querySelector('#trial-label').textContent=`Trial ${trialInBlock+1} of ${currentBlock().trials}`;document.querySelector('#progress-label').textContent=`${globalTrial+1} / ${totalTrials}`;game.classList.toggle('sway-active',currentBlock().moving)}
function startExperiment(){const id=document.querySelector('#participant-id').value.trim();if(!id){alert('Enter a Participant ID first.');return}participantId=id;startScreen.classList.add('hidden');experimentScreen.classList.remove('hidden');resetForReady();requestAnimationFrame(render)}
function resetForReady(){trialActive=false;trialReady=true;target.style.display='none';cursor.style.display='block';message.style.display='block';message.textContent=currentBlock().moving?'Sway condition: the target will move slowly left, right, up, and down. Start from the blue circle.':'Move into the start circle and click to begin.';mouseBuffer=[];previousShown=null;updateLabels()}
function getLocalPointer(e){const r=game.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}} function startCenter(){return{x:game.clientWidth/2,y:game.clientHeight*.86}}
function beginTrial(){const b=currentBlock();trialReady=false;trialActive=true;movementOnsetAt=null;pathLength=0;maxProjection=0;previousShown=null;const margin=170;targetBaseX=margin+Math.random()*Math.max(1,game.clientWidth-margin*2);targetBaseY=game.clientHeight*.22;swayStart=performance.now();targetShownAt=performance.now();target.style.display='block';message.style.display='none';const s=startCenter();rawMouse={...s};shownMouse={...s};mouseBuffer=[{t:performance.now()-b.delay-5,x:s.x,y:s.y},{t:performance.now(),x:s.x,y:s.y}]}
function targetPosition(now=performance.now()){const b=currentBlock();let x=targetBaseX,y=targetBaseY;if(b.moving){const seconds=(now-swayStart)/1000;const a=2*Math.PI*SWAY_FREQUENCY*seconds;x+=SWAY_X*Math.sin(a);y+=SWAY_Y*Math.sin(a*0.73+Math.PI/3)}return{x,y}}
function delayedPosition(now){const delay=currentBlock().delay;if(delay===0)return{...rawMouse};const wanted=now-delay;while(mouseBuffer.length>2&&mouseBuffer[1].t<wanted)mouseBuffer.shift();if(mouseBuffer.length===1)return{x:mouseBuffer[0].x,y:mouseBuffer[0].y};const a=mouseBuffer[0],b=mouseBuffer[1];if(wanted<=a.t)return{x:a.x,y:a.y};if(wanted>=b.t)return{x:b.x,y:b.y};const p=(wanted-a.t)/(b.t-a.t);return{x:a.x+(b.x-a.x)*p,y:a.y+(b.y-a.y)*p}}
function render(now){if(!experimentScreen.classList.contains('hidden')){shownMouse=delayedPosition(now);cursor.style.left=`${shownMouse.x}px`;cursor.style.top=`${shownMouse.y}px`;if(trialActive){const tp=targetPosition(now);target.style.left=`${tp.x}px`;target.style.top=`${tp.y}px`;if(previousShown)pathLength+=distance(previousShown,shownMouse);previousShown={...shownMouse};if(movementOnsetAt===null&&distance(shownMouse,startCenter())>=MOVEMENT_THRESHOLD)movementOnsetAt=now;const s=startCenter(),vx=tp.x-s.x,vy=tp.y-s.y,len=Math.hypot(vx,vy)||1,projection=((shownMouse.x-s.x)*vx+(shownMouse.y-s.y)*vy)/len;maxProjection=Math.max(maxProjection,projection-len)}}requestAnimationFrame(render)}
function finishTrial(now){const b=currentBlock(),tp=targetPosition(now),error=distance(shownMouse,tp),onset=movementOnsetAt??targetShownAt;data.push({participant_id:participantId,global_trial:globalTrial+1,phase:b.name,phase_trial:trialInBlock+1,recorded:b.record,delay_ms:b.delay,target_motion:b.moving?'slow_2d_sway':'stationary',sway_x_px:b.moving?SWAY_X:0,sway_y_px:b.moving?SWAY_Y:0,sway_frequency_hz:b.moving?SWAY_FREQUENCY:0,reaction_time_ms:Math.round(onset-targetShownAt),movement_time_ms:Math.round(now-onset),total_trial_time_ms:Math.round(now-targetShownAt),endpoint_error_px:Number(error.toFixed(2)),hit:error<=32,overshoot_px:Number(Math.max(0,maxProjection).toFixed(2)),path_length_px:Number(pathLength.toFixed(2)),viewport_width_px:game.clientWidth,viewport_height_px:game.clientHeight});trialActive=false;target.style.display='none';advanceTrial()}
function advanceTrial(){globalTrial++;trialInBlock++;if(trialInBlock>=currentBlock().trials){blockIndex++;trialInBlock=0}if(blockIndex>=BLOCKS.length){finishExperiment();return}setTimeout(resetForReady,350)}
game.addEventListener('pointermove',e=>{rawMouse=getLocalPointer(e);mouseBuffer.push({t:performance.now(),x:rawMouse.x,y:rawMouse.y});if(mouseBuffer.length>500)mouseBuffer.shift()});game.addEventListener('pointerdown',e=>{const p=getLocalPointer(e);if(trialReady){if(distance(p,startCenter())<=34)beginTrial();return}if(trialActive)finishTrial(performance.now())});
function finishExperiment(){experimentScreen.classList.add('hidden');resultsScreen.classList.remove('hidden');const recorded=data.filter(d=>d.recorded),hits=recorded.filter(d=>d.hit).length,mean=(arr,key)=>arr.reduce((s,r)=>s+r[key],0)/Math.max(1,arr.length);document.querySelector('#metric-trials').textContent=recorded.length;document.querySelector('#metric-hit-rate').textContent=`${Math.round(hits/recorded.length*100)}%`;document.querySelector('#metric-time').textContent=`${Math.round(mean(recorded,'movement_time_ms'))} ms`;document.querySelector('#metric-error').textContent=`${mean(recorded,'endpoint_error_px').toFixed(1)} px`;document.querySelector('#summary-text').textContent=`Participant ${participantId} completed the experiment. Download the CSV before starting another participant.`}
function downloadCSV(){const headers=Object.keys(data[0]||{}),rows=[headers.join(','),...data.map(r=>headers.map(h=>JSON.stringify(r[h])).join(','))],blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`visuomotor_${participantId}_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#start-btn').addEventListener('click',startExperiment);document.querySelector('#download-btn').addEventListener('click',downloadCSV);document.querySelector('#restart-btn').addEventListener('click',()=>location.reload());
