const BLOCKS=[{name:'Practice',trials:2,movingTargets:false,sceneMotion:false,record:false},{name:'Baseline',trials:10,movingTargets:false,sceneMotion:false,record:true},{name:'Moving Targets',trials:10,movingTargets:true,sceneMotion:false,record:true},{name:'Moving Visual Field',trials:10,movingTargets:true,sceneMotion:true,record:true},{name:'Restored',trials:10,movingTargets:false,sceneMotion:false,record:true}];
const COLORS=['red','blue','green','yellow','purple'],SHAPES=['circle','square','triangle'];
const startScreen=document.querySelector('#start-screen'),exp=document.querySelector('#experiment-screen'),results=document.querySelector('#results-screen'),game=document.querySelector('#game-area'),scene=document.querySelector('#scene'),layer=document.querySelector('#objects-layer'),promptEl=document.querySelector('#target-prompt'),fixation=document.querySelector('#fixation'),feedback=document.querySelector('#feedback');
let pid='',bi=0,ti=0,gi=0,data=[],waiting=false,responded=false,trialStart=0,phaseStart=0,timer=null,raf=0,correctCount=0,target=null,stimuli=[];const total=BLOCKS.reduce((s,b)=>s+b.trials,0),cur=()=>BLOCKS[bi];
const rand=(a,b)=>Math.random()*(b-a)+a,choice=a=>a[Math.floor(Math.random()*a.length)];
function labels(){document.querySelector('#phase-label').textContent=cur().name;document.querySelector('#trial-label').textContent=`Trial ${ti+1} of ${cur().trials}`;document.querySelector('#progress-label').textContent=`${gi+1} / ${total}`;document.querySelector('#correct-label').textContent=correctCount}
function start(){pid=document.querySelector('#participant-id').value.trim();if(!pid){alert('Enter a Participant ID.');return}startScreen.classList.add('hidden');exp.classList.remove('hidden');phaseStart=performance.now();labels();prepareTrial();raf=requestAnimationFrame(animate)}
function prepareTrial(){clearTimeout(timer);responded=false;waiting=true;stimuli=[];layer.innerHTML='';feedback.textContent='';feedback.className='';fixation.classList.remove('hidden');promptEl.textContent='GET READY';scene.style.transform='none';timer=setTimeout(showStimuli,Math.round(rand(650,1450)))}
function getPosition(){let x,y,tries=0;do{x=rand(13,87);y=rand(28,80);tries++}while(stimuli.some(s=>Math.hypot(s.x-x,s.y-y)<14)&&tries<50);return{x,y}}
function makeStimulus(color,shape,isTarget,i){const p=getPosition(),el=document.createElement('button');el.type='button';el.className=`stimulus ${color} ${shape}`;el.setAttribute('aria-label',`${color} ${shape}`);el.style.left=p.x+'%';el.style.top=p.y+'%';el.dataset.target=isTarget?'1':'0';el.dataset.index=i;el.addEventListener('pointerdown',respond);layer.appendChild(el);const s={el,x:p.x,y:p.y,vx:rand(-.075,.075),vy:rand(-.065,.065),isTarget,color,shape};stimuli.push(s);return s}
function showStimuli(){waiting=false;fixation.classList.add('hidden');const color=choice(COLORS),shape=choice(SHAPES);target={color,shape};promptEl.textContent=`${color.toUpperCase()} ${shape.toUpperCase()}`;stimuli=[];const combos=[];COLORS.forEach(c=>SHAPES.forEach(s=>{if(c!==color||s!==shape)combos.push([c,s])}));combos.sort(()=>Math.random()-.5);const targetSlot=Math.floor(Math.random()*8);for(let i=0;i<8;i++){const isTarget=i===targetSlot;let c,s;if(isTarget){c=color;s=shape}else{const pair=combos[i<targetSlot?i:i-1];c=pair[0];s=pair[1]}makeStimulus(c,s,isTarget,i)}trialStart=performance.now()}
function respond(e){if(waiting||responded)return;responded=true;const now=performance.now(),el=e.currentTarget,isCorrect=el.dataset.target==='1',rt=Math.round(now-trialStart),targetStim=stimuli.find(s=>s.isTarget);let clickError=0;if(targetStim){const tr=targetStim.el.getBoundingClientRect();clickError=Math.hypot(e.clientX-(tr.left+tr.width/2),e.clientY-(tr.top+tr.height/2))}if(isCorrect){correctCount++;feedback.textContent=`CORRECT  ${rt} ms`;feedback.className='correct'}else{feedback.textContent=`INCORRECT  ${rt} ms`;feedback.className='wrong'}document.querySelector('#rt-label').textContent=rt+' ms';data.push({participant_id:pid,global_trial:gi+1,phase:cur().name,phase_trial:ti+1,recorded:cur().record,target_color:target.color,target_shape:target.shape,moving_targets:cur().movingTargets,moving_visual_field:cur().sceneMotion,correct:isCorrect?1:0,reaction_time_ms:rt,click_error_px:Number(clickError.toFixed(2))});labels();timer=setTimeout(nextTrial,550)}
function nextTrial(){gi++;ti++;if(ti>=cur().trials){bi++;ti=0;phaseStart=performance.now()}if(bi>=BLOCKS.length){finish();return}labels();prepareTrial()}
function animate(now){if(exp.classList.contains('hidden'))return;const t=(now-phaseStart)/1000;if(cur().sceneMotion){const x=Math.sin(t*1.15)*28+Math.sin(t*.43)*12,y=Math.cos(t*.91)*18,rot=Math.sin(t*.68)*4.5,scale=1+Math.sin(t*.55)*.018;scene.style.transform=`translate(${x}px,${y}px) rotate(${rot}deg) scale(${scale})`}else scene.style.transform='none';if(cur().movingTargets&&!waiting&&!responded){stimuli.forEach(s=>{s.x+=s.vx;s.y+=s.vy;if(s.x<9||s.x>91)s.vx*=-1;if(s.y<23||s.y>86)s.vy*=-1;s.el.style.left=s.x+'%';s.el.style.top=s.y+'%'})}raf=requestAnimationFrame(animate)}
function finish(){clearTimeout(timer);cancelAnimationFrame(raf);exp.classList.add('hidden');results.classList.remove('hidden');const d=data.filter(x=>x.recorded),correct=d.filter(x=>x.correct===1),mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;document.querySelector('#metric-trials').textContent=d.length;document.querySelector('#metric-accuracy').textContent=(100*correct.length/Math.max(1,d.length)).toFixed(1)+'%';document.querySelector('#metric-rt').textContent=Math.round(mean(correct.map(x=>x.reaction_time_ms)))+' ms';document.querySelector('#metric-fastest').textContent=(correct.length?Math.min(...correct.map(x=>x.reaction_time_ms)):0)+' ms';document.querySelector('#metric-errors').textContent=d.length-correct.length;document.querySelector('#metric-click-error').textContent=mean(d.map(x=>x.click_error_px)).toFixed(1)+' px';document.querySelector('#summary-text').textContent=`Participant ${pid} completed the visual reaction experiment. Trial-level reaction time and accuracy are ready for analysis.`}
document.querySelector('#start-btn').addEventListener('click',start);document.querySelector('#restart-btn').addEventListener('click',()=>location.reload());document.querySelector('#download-btn').addEventListener('click',()=>{if(!data.length)return;const h=Object.keys(data[0]),rows=[h.join(','),...data.map(r=>h.map(k=>JSON.stringify(r[k])).join(','))],a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download=`visual_reaction_${pid}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});