const BLOCKS=[{name:'Practice',trials:2,shift:0,sway:5,record:false},{name:'Baseline',trials:5,shift:0,sway:8,record:true},{name:'Shifted Vision',trials:12,shift:55,sway:14,record:true},{name:'Restored',trials:12,shift:0,sway:8,record:true}];
const ORDER=[20,1,18,4,13,6,10,15,2,17,3,19,7,16,8,11,14,9,12,5];
const startScreen=document.querySelector('#start-screen'),exp=document.querySelector('#experiment-screen'),results=document.querySelector('#results-screen'),game=document.querySelector('#game-area'),board=document.querySelector('#dartboard'),aim=document.querySelector('#aim'),msg=document.querySelector('#message'),scoreLabel=document.querySelector('#score-label'),dartLayer=document.querySelector('#dart-layer');
let pid='',bi=0,ti=0,gi=0,active=false,mouse={x:0,y:0},startAt=0,data=[],raf=0;const total=BLOCKS.reduce((s,b)=>s+b.trials,0);const cur=()=>BLOCKS[bi];
function makeNumbers(){const box=500,r=239,c=box/2,n=document.querySelector('#numbers');ORDER.forEach((v,i)=>{const a=(i*18-90)*Math.PI/180,e=document.createElement('div');e.className='board-number';e.textContent=v;e.style.left=`${c+Math.cos(a)*r}px`;e.style.top=`${c+Math.sin(a)*r}px`;e.style.transform='translate(-50%,-50%)';n.appendChild(e)})}makeNumbers();
function labels(){document.querySelector('#phase-label').textContent=cur().name;document.querySelector('#trial-label').textContent=`Dart ${ti+1} of ${cur().trials}`;document.querySelector('#progress-label').textContent=`${gi+1} / ${total}`}
function local(e){const r=game.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function start(){const v=document.querySelector('#participant-id').value.trim();if(!v){alert('Enter a Participant ID.');return}pid=v;startScreen.classList.add('hidden');exp.classList.remove('hidden');const r=game.getBoundingClientRect();mouse={x:r.width/2,y:r.height/2};active=true;startAt=performance.now();labels();msg.textContent='Aim at the dartboard. Click to throw.';raf=requestAnimationFrame(render)}
function boardGeom(){const g=game.getBoundingClientRect(),b=board.getBoundingClientRect();return{cx:b.left-g.left+b.width/2,cy:b.top-g.top+b.height/2,R:b.width/2,scale:b.width/500}}
function aimPos(now){const b=cur(),t=(now-startAt)/1000;const sx=Math.sin(t*4.1)*b.sway+Math.sin(t*7.7+1.3)*b.sway*.45,sy=Math.cos(t*3.5+.4)*b.sway*.8+Math.sin(t*6.3)*b.sway*.35;return{x:mouse.x+sx+b.shift,y:mouse.y+sy}}
function render(now){if(!active)return;const p=aimPos(now);aim.style.left=p.x+'px';aim.style.top=p.y+'px';raf=requestAnimationFrame(render)}
function scoreAt(x,y){const g=boardGeom(),dx=(x-g.cx)/g.scale,dy=(y-g.cy)/g.scale,r=Math.hypot(dx,dy);if(r>227)return{score:0,label:'MISS',r};if(r<=11)return{score:50,label:'BULL',r};if(r<=24)return{score:25,label:'25',r};let deg=(Math.atan2(dy,dx)*180/Math.PI+99+360)%360,idx=Math.floor(deg/18)%20,num=ORDER[idx],mult=1;if(r>=127&&r<=145)mult=3;else if(r>=205&&r<=227)mult=2;return{score:num*mult,label:mult===3?'T'+num:mult===2?'D'+num:String(num),r}}
function throwDart(){if(!active)return;const now=performance.now(),p=aimPos(now),g=boardGeom(),s=scoreAt(p.x,p.y),mark=document.createElement('div');mark.className='dart-hit';mark.style.left=((p.x-g.cx)/g.scale+250)+'px';mark.style.top=((p.y-g.cy)/g.scale+250)+'px';dartLayer.appendChild(mark);scoreLabel.textContent=`${s.label} (${s.score})`;data.push({participant_id:pid,global_dart:gi+1,phase:cur().name,phase_dart:ti+1,recorded:cur().record,visual_shift_px:cur().shift,sway_amplitude_px:cur().sway,score:s.score,landing_label:s.label,bull_error_px:Number(s.r.toFixed(2)),throw_time_ms:Math.round(now-startAt)});active=false;setTimeout(next,650)}
function next(){gi++;ti++;if(ti>=cur().trials){bi++;ti=0}if(bi>=BLOCKS.length){finish();return}dartLayer.innerHTML='';labels();startAt=performance.now();active=true;raf=requestAnimationFrame(render)}
function finish(){cancelAnimationFrame(raf);exp.classList.add('hidden');results.classList.remove('hidden');const d=data.filter(x=>x.recorded),mean=(k)=>d.reduce((s,x)=>s+x[k],0)/Math.max(1,d.length);document.querySelector('#metric-trials').textContent=d.length;document.querySelector('#metric-score').textContent=mean('score').toFixed(1);document.querySelector('#metric-error').textContent=mean('bull_error_px').toFixed(1)+' px';document.querySelector('#metric-bulls').textContent=d.filter(x=>x.score===50).length;document.querySelector('#summary-text').textContent=`Participant ${pid} completed the dart adaptation task.`}
game.addEventListener('pointermove',e=>{mouse=local(e)});game.addEventListener('pointerdown',throwDart);document.querySelector('#start-btn').addEventListener('click',start);document.querySelector('#restart-btn').addEventListener('click',()=>location.reload());document.querySelector('#download-btn').addEventListener('click',()=>{const h=Object.keys(data[0]||{}),rows=[h.join(','),...data.map(r=>h.map(k=>JSON.stringify(r[k])).join(','))],a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download=`dart_adaptation_${pid}.csv`;a.click();URL.revokeObjectURL(a.href)});